### ISSUE TITLE
安装成功，重启后插件设置页面加载报错

### ISSUE THREAD

**Issue by lizhuangs** [chengww5217/picgo-plugin-qingstor-uploader#2]
在线安装成功后重启，然后点插件设置就报错了。找了一天才发现是这个插件的问题。。。
2019-05-26 01:44:37 [PicGo ERROR] Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-qingstor-uploader'
------Error Stack Begin------
Error: Cannot find module 'C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-qingstor-uploader'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (D:\Program Files\picGo\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at PluginLoader.getPlugin (D:\Program Files\picGo\resources\app.asar\node_modules\picgo\dist\lib\PluginLoader.js:76:16)
    at PluginLoader.load (D:\Program Files\picGo\resources\app.asar\node_modules\picgo\dist\lib\PluginLoader.js:57:26)
    at PicGo.init (D:\Program Files\picGo\resources\app.asar\node_modules\picgo\dist\core\PicGo.js:61:31)
    at new PicGo (D:\Program Files\picGo\resources\app.asar\node_modules\picgo\dist\core\PicGo.js:36:14)
    at X (D:\Program Files\picGo\resources\app.asar\dist\electron\main.js:1:61121)
-------Error Stack End-------
把插件删除后，安装其它的插件`picgo-plugin-github-plus`可以正常使用。基本断定是这个插件的问题。系统环境是win8.1，node10，picgo2.1.2。插件安装页面显示是1.1.9，但是源码里面我看到的是1.2。

**Comment by chengww5217** [comment]
我在 `win 10 专业版， node: '10.15.3' ` 上是正常安装的。

![QQ截图20190526120926](https://user-images.githubusercontent.com/34536334/58377273-1df34f80-7faf-11e9-84fe-ecdc735f8a6f.png)

你这种情况应该是插件没有正常安装，这边先 cd 到 `C:\Users\Administrator\AppData\Roaming\picgo\node_modules\`

然后运行 `npm uninstall picgo-plugin-qingstor-uploader` 卸载插件，如卸载不成功直接删除 `picgo-plugin-qingstor-uploader` 文件夹。

而后重启应用再次安装插件看能否成功。

**Comment by lizhuangs** [comment]
我卸载重装了好多次了。。package.json里面都手动删除过。可以安装，但是打开插件设置界面就报这个错了。

**Comment by chengww5217** [comment]
那我明天去找个 win 8.1 的虚拟机测试下看下到底是什么问题

**Comment by chengww5217** [comment]
我这边暂时还找不到 `win 8.1` 的虚拟机，现在还定位不到问题。但是我试过很多其他版本的 win 虚拟机都是 OK 的。 这个问题可能是 node 版本导致的，这边看升级 node 版本是否能解决问题呢。

**Comment by lizhuangs** [comment]
呃，我node版本和你的是一样的10.15.3。我重装了node，清除了npm_cache、nodee_modules、Roaming\picgo，重装了picgo还是这个问题。。

**Comment by lizhuangs** [comment]
我今天在win10上面测试，node8和10都没有问题。。。

**Comment by chengww5217** [comment]
看来是操作系统的差异导致的 `node module` 安装不上了

**Comment by lizhuangs** [comment]
问题是我其它插件可以装上，你这个里面是不是用了什么不兼容的东西:joy::joy::joy:。。

**Comment by chengww5217** [comment]
源代码就那么一点，应该不至于吧。我没做过前端的项目，这个都是用的官方的插件模板弄得。编译器是 ideaJ IDEA，有问题我觉得也是编译器的问题。
